ATEN: refactor activate function
Move activation check to separate function, and use it during BIOS flash

diff --git a/redirector-ATEN b/redirector-ATEN
--- a/redirector-ATEN
+++ b/redirector-ATEN
@@ -159,6 +159,13 @@ ATEN_sol()
     ipmitool -I lanplus -H $hostip_nb -p 623 -U $opt_user -P $opt_passwd sol activate
 }
 
+ATEN_sm_lic_check()
+{
+    local cookies="langSetFlag=0;language=English;SID=$session;mainpage=maintenance;subpage=main_bios_upload"
+    local get="$curl -b $cookies https://$hostip"
+    $get/cgi/url_redirect.cgi?url_name=misc_license | fgrep -q '		license_activated()' && return 0 || return 1
+}
+
 ATEN_activate()
 {
     [ -n "$1" ] || error "License file not specified"
@@ -173,14 +180,11 @@ ATEN_activate()
     # key usually shipped as <MAC>;;key
     key=$(echo "${key##*;;}"|awk -F"-" '{ for (i=1; i<=NF; i++) printf "%s","&bioskey"(i-1)"="$i }')
     local fmt='+%a%%20%b%%20%d%%20%Y%%20%T%%20GMT%z%%20(%Z)'
-    local cookies="langSetFlag=0;language=English;SID=$session;mainpage=maintenance;subpage=main_bios_upload"
-    local get="$curl -b $cookies https://$hostip"
     echo -n 'Checking activation status...'
-    $get/cgi/url_redirect.cgi?url_name=misc_license | fgrep -q '		license_activated()' && error Activated || echo 'Not activated'
-    # very similar to fw update
+    ATEN_sm_lic_check && error 'Activated' || echo 'Not activated, good'
     echo -n 'Sending activation key...'
-    cookies="langSetFlag=0;language=English;SID=$session;mainpage=miscellaneous;subpage=misc_license"
-    get="$curl -b $cookies https://$hostip"
+    local cookies="langSetFlag=0;language=English;SID=$session;mainpage=miscellaneous;subpage=misc_license"
+    local get="$curl -b $cookies https://$hostip"
     $get/cgi/ipmi.cgi -d "BIOS_LINCENSE_ACTIVATE.XML=(0,0)&time_stamp=$(LC_ALL=C date "$fmt")$key" | fgrep -q 'BIOS_LINCESNE CHECK="1"' && echo 'OK!' \
         || error 'Failed to activate :('
     echo 'License activated successfully'
@@ -252,6 +256,8 @@ ATEN_lan_set()
      biosup) shift
         [ -n "$1" ] || error "BIOS file not specified"
         [ -e "$1" ] || error "File \`$1' not exists"
+        echo 'Checking BIOS license status...'
+        ATEN_sm_lic_check && echo 'Activated' || error 'Not activated, exiting...'
         local cookies="langSetFlag=0;language=English;SID=$session;mainpage=maintenance;subpage=main_bios_upload"
         local get="$curl -b $cookies https://$hostip"
         echo -n "Preparing BMC to flash [$session]..."
