redirector: portability fixes
Now it should work on MacOS and *BSD (untested)

diff --git a/redirector-ATEN b/redirector-ATEN
--- a/redirector-ATEN
+++ b/redirector-ATEN
@@ -31,7 +31,7 @@ ATEN_mc_info()
          -d "Get_BoradID_XML.XML=(0,0)" \
          "http://$hostip/cgi/ipmi.cgi" | parse_xml`
     cat <<EOF
-Firmware Revision         : $(echo $GENERIC_IPMIFW_VERSION | sed 's,\(..\),\1.,' | xargs printf "%.2f")
+Firmware Revision         : $(echo $GENERIC_IPMIFW_VERSION | $sed 's,\(..\),\1.,' | xargs printf "%.2f")
 Firmware Tag              : $GENERIC_IPMIFW_TAG
 Build Time                : $GENERIC_IPMIFW_BLDTIME
 Kernel Version            : $KERNAL_VERSION
@@ -82,11 +82,11 @@ ATEN_redirect()
         ATEN_kvm "$1" || rc=$?
         [ "$rc" -eq 0 -o "$rc" -eq 18 ] || return $rc
         s=$(stat -c%s $3)
-        cnt="$(sed -n 's,[[:space:]]*<argument>\([^<]\+\)</argument>,\1,p' "$1" | wc -l)"
+        cnt="$($sed -n 's,[[:space:]]*<argument>\([^<]\+\)</argument>,\1,p' "$1" | wc -l)"
         rev=r1
         [ "$cnt" -ne 8 ] || rev=r2
-        sed -n 's,[[:space:]]*<argument>\([^<]\+\)</argument>,\1,p' "$1" | tr '\n' ' ' |
-            sed "s,^,$3 $(((s - (s * 277) / 10000) / 1024)) $opt_timeout $rev ," |
+        $sed -n 's,[[:space:]]*<argument>\([^<]\+\)</argument>,\1,p' "$1" | tr '\n' ' ' |
+            $sed "s,^,$3 $(((s - (s * 277) / 10000) / 1024)) $opt_timeout $rev ," |
                 timeout_pass -9 $((opt_timeout * 60 + 15)) java -cp $java_path/redirector.jar com.redirerctor.ATEN.kvm.Redirector
         ;;
     *)
@@ -104,7 +104,8 @@ ATEN_lan_print()
 
 ATEN_lan_set()
 {
-    local get="$curl -b SID=$session http://$hostip"
+    local cookies="langSetFlag=0;language=English;SID=$session;mainpage=maintenance;subpage=main_fw_update"
+    local get="$curl -b $cookies http://$hostip"
     local fmt='+%a%%20%b%%20%d%%20%Y%%20%T%%20GMT%z%%20(%Z)'
     local cnt=0
 
@@ -113,17 +114,27 @@ ATEN_lan_set()
         [ -n "$1" ] || error "Image file not specified"
         [ -e "$1" ] || error "File \`$1' not exists"
         echo -n "Preparing BMC to flash [$session]..."
-        $get/cgi/ipmi.cgi -G -d "LOCK_UPLOAD_FW.XML=(0,0)&time_stamp=$(LC_ALL=C date "$fmt")" | fgrep -q 'RES="1"' && echo done || error failed
+	$get/cgi/ipmi.cgi -d "LOCK_UPLOAD_FW.XML=(0,0)&time_stamp=$(LC_ALL=C date "$fmt")" | fgrep -q 'RES="1"' && echo done || error failed
         echo -n "Uploading image..."
-        $get/cgi/oem_firmware_upload.cgi -m 300 -H 'Expect:' -f -F "form1=@$1;filename=firmware.bin;type=application/octet-stream" | fgrep -q 'UpgradeFW' && echo done || error failed
-        echo "Flashing..."
-        $get/cgi/oem_firmware_update.cgi -G -d "preserve_config=0&timeStamp=$(LC_ALL=C date "$fmt")" | egrep -q '^ok' || error 'startflash failed'
-        while sleep 10; do
-            percent=`$get/cgi/upgrade_process.cgi -G -d "time_stamp=$(LC_ALL=C date "$fmt")" | sed -n 's,<percent>\([0-9 ]\+\)</percent>,\1,p'` ||:
+	$get/cgi/oem_firmware_upload.cgi -m 300 -H 'Expect:' -f -F "\"form1\"=@$1;filename=\"$(basename $1)\";type=application/octet-stream" | fgrep -q 'btn_upgrade' && echo done || error failed
+	replace=`$get/cgi/ipmi.cgi -d "UPLOAD_FW_VERSION.XML=(0,0)&time_stamp=$(LC_ALL=C date "$fmt")" | $sed -n 's,.*FW_VERSION\ \(NEW=.*"\)\/.*,\1,p'` || error failed
+	echo "Going to replace FW -> $replace..."
+	echo "Flashing..."
+	fwreply=`$get/cgi/oem_firmware_update.cgi -m 5 -d "preserve_config=1&preserve_sdr=1&timeStamp=$(LC_ALL=C date "$fmt")" ||:`
+	[ -n "$fwreply" ] || error 'startflash failed'
+	case "$fwreply" in
+		ok) percent=`$get/cgi/upgrade_process.cgi -d "fwtype=0&time_stamp=$(LC_ALL=C date "$fmt")" | $sed -n 's,.*<percent>\([0-9 ]\+\)</percent>,\1,p'` ||:
+		    printf "\rCompleted %s%%" "$percent"
+			;;
+		 *) error 'startflash falied'
+			;;
+	esac
+	while sleep 5; do
+            percent=`$get/cgi/upgrade_process.cgi -d "fwtype=0&time_stamp=$(LC_ALL=C date "$fmt")" | $sed -n 's,.*<percent>\([0-9 ]\+\)</percent>,\1,p'` ||:
             printf "\rCompleted %s%%" "$percent"
             [ "$percent" != 100 ] || break
             cnt=$((cnt+1))
-            [ "$cnt" -lt 5 ] || [ -n "$percent" -o "$percent" -ne 0 ] || error failed
+            [ "$cnt" -lt 15 ] || [ -n "$percent" -o "$percent" -ne 0 ] || error failed
         done
         printf "\nFlash complete. Rebooting...\n"
         session=
